name: Compilar y Desplegar

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/compilar-y-desplegar.yml'
      - 'GithubActionsDemoApp/**'
      - 'Pruebas/**'
    branches: 
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    # Permisos para escribir el Release
    permissions: 
      contents: write
    env:
      proyecto: GithubActionsDemoApp/GithubActionsDemoApp.csproj      
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      # Instalamos .NET
      - name: Instalar .NET
        uses: actions/setup-dotnet@v5.2.0
        with:
          dotnet-version: 8.0.x

      - name: Obteniendo las dependencias
        run: dotnet restore

      - name: Compilar
        run: dotnet build --no-restore # Para no restuarar porque ya lo hicimos en el anterior paso
        
      - name: Realizar Pruebas
        run: dotnet test --no-build

      # El artefacto lo dejará en la carpeta miapp
      - name: dotnet publish
        run: dotnet publish $proyecto  -c Release -o miapp --runtime win-x86

      # El contenido de la carpeta miapp, quiero ponerla como artefacto para que otros puedan descargarla
      # Upload a Build Artifact lo buscamos del market place de workflows
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        # Especificamos donde se encuentra el artifacto
        with:
          name: build
          path: ./miapp

      # Vamos a comprimir nuestro artefacto publish a un zip
      - name: Zip
        if: startsWith(github.ref_name, 'refs/tags/')
        run: zip -r mi_app.zip ./miapp

      # Usamos el action del market place
      # para colocar el release en el repositorio
      - name: GH Release
        uses: softprops/action-gh-release@v2.6.1
        if: startsWith(github.ref_name, 'refs/tags/')
        with: 
          files: ./mi_app.zip
          body: "Nuestra aplicacion"
          # Nombre que le vamos a colocar a la etiqueta
          # En este caso vamos colocar el nombre de la rama
          tag_name: ${{ github.ref_name }}
      
      
